### ISSUE TITLE
Using OpenPose for getting skeleton data from ntu rgb videos

### ISSUE THREAD

**Issue by jug971990** [huguyuehuhu/HCN_pytorch#34]
Initially , I edited your read_xyz function to get 2D coordinates instead of 3D coordinates from the raw skeleton data downloaded from ntu dataset website.  I used two classes "A44" and "A26". I changed the num_class to 2 and input_channels to 2.  I trained the model and the evaluation accuracy was 99.5%.

Now for the same two classes, I extracted 2D skeleton data from OpenPose and preprocessed the data. When I ran the code for training the model , I see that the training and evaluation accuracy are around 45 - 50 %. 

Please let me know why this is happening?

**Comment by huguyuehuhu** [comment]
Obtaining ~50% for a 2-class task means that 1) the model learned nothing but outputted a random guess, 2) OR More Likely, there is something wrong in your dataset (e.g, data  and label are misaligned). You can change the HCN model  into a simple 3 layers MLP to examine whether your data processing is correct.  Please also refer to #12.
