### ISSUE TITLE
params.train_feeder_args["num_frame_path"]

### ISSUE THREAD

**Issue by PJJie** [huguyuehuhu/HCN_pytorch#48]
请问params.train_feeder_args["num_frame_path"]的数据是从哪里来的？

**Comment by huguyuehuhu** [comment]
Please refer to the [corresponding code](https://github.com/huguyuehuhu/HCN-pytorch/blob/98b15c5c6128ba843231486f5e040728d265c1a7/data_loader.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L19) in the `data_loader.py`.
